<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="5" skipped="0" tests="10" time="0.095" timestamp="2022-03-15T18:43:35.267778" hostname="eugeniy-Lenovo-IdeaPad-S510p"><testcase classname="test_stat.Test_stat" name="test_stat_1" time="0.001" /><testcase classname="test_stat.Test_stat" name="test_stat_2" time="0.002"><failure message="assert 1 == 0&#10;  +1&#10;  -0">self = &lt;test_stat.Test_stat object at 0x7f53b2f7f4c0&gt;

    def test_stat_2(self):
        result = stat_2()
&gt;       assert result % 2 == 0
E       assert 1 == 0
E         +1
E         -0

test_stat.py:13: AssertionError</failure></testcase><testcase classname="test_stat.Test_stat" name="test_stat_3" time="0.002"><failure message="assert 1 == 0&#10;  +1&#10;  -0">self = &lt;test_stat.Test_stat object at 0x7f53b2f02520&gt;

    def test_stat_3(self):
        result = stat_3()
&gt;       assert result % 2 == 0
E       assert 1 == 0
E         +1
E         -0

test_stat.py:17: AssertionError</failure></testcase><testcase classname="test_stat.Test_stat" name="test_stat_4" time="0.001"><failure message="assert 1 == 0&#10;  +1&#10;  -0">self = &lt;test_stat.Test_stat object at 0x7f53b2f54d60&gt;

    def test_stat_4(self):
        result = stat_4()
&gt;       assert result % 2 == 0
E       assert 1 == 0
E         +1
E         -0

test_stat.py:21: AssertionError</failure></testcase><testcase classname="test_stat.Test_stat" name="test_stat_5" time="0.001"><failure message="assert 1 == 0&#10;  +1&#10;  -0">self = &lt;test_stat.Test_stat object at 0x7f53b2f13400&gt;

    def test_stat_5(self):
        result = stat_5()
&gt;       assert result % 2 == 0
E       assert 1 == 0
E         +1
E         -0

test_stat.py:25: AssertionError</failure></testcase><testcase classname="test_stat.Test_stat" name="test_stat_6" time="0.001" /><testcase classname="test_stat.Test_stat" name="test_stat_7" time="0.001" /><testcase classname="test_stat.Test_stat" name="test_stat_8" time="0.001" /><testcase classname="test_stat.Test_stat" name="test_stat_9" time="0.001"><failure message="assert 1 == 0&#10;  +1&#10;  -0">self = &lt;test_stat.Test_stat object at 0x7f53b2f1bd90&gt;

    def test_stat_9(self):
        result = stat_9()
&gt;       assert result % 2 == 0
E       assert 1 == 0
E         +1
E         -0

test_stat.py:41: AssertionError</failure></testcase><testcase classname="test_stat.Test_stat" name="test_stat_10" time="0.001" /></testsuite></testsuites>